<a href="https://colab.research.google.com/github/newman001/my_learning_progress/blob/master/pytorch_fully_connected_layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import torch

x = torch.tensor([[10., 20.]])

fc = torch.nn.Linear(2, 3)

w = torch.tensor([[11., 12.], [21., 22.], [31., 32]])
fc.weight.data = w

b = torch.tensor([[31., 32., 33.]])
fc.bias.data = b

fc_out = fc(x)
print(fc_out)
fc_out_alternative = torch.mm(x, w.t()) + b
print(fc_out_alternative)
print(fc_out == fc_out_alternative)

tensor([[381., 682., 983.]], grad_fn=<AddmmBackward>)
tensor([[381., 682., 983.]])
tensor([[1, 1, 1]], dtype=torch.uint8)
